apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental-service-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  