apiVersion: v1
kind: Service
metadata:
  name: housing-service
spec:
  selector:
    app: housing-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  