apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation-service-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
  